apiVersion: v2
appVersion: 0.0.1
description: A Helm chart for macropower-analytics-panel-server
engine: gotpl
home: https://github.com/giantswarm/macropower-analytics-panel-server-app
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
name: macropower-analytics-panel-server
sources:
- https://github.com/MacroPower/macropower-analytics-panel/tree/master/server
version: [[ .Version ]]
annotations:
  config.giantswarm.io/version: "analytics-user-data"
  application.giantswarm.io/team: "atlas"
