name: macropower-analytics-panel-server
namespace: monitoring
serviceType: managed

global:
  podSecurityStandards:
    enforced: false

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

server:
  args: []

  image:
    name: giantswarm/macropower-analytics-panel-server
    tag: 0.0.1
    pullPolicy: IfNotPresent
  port: 8080

  service:
    port: 8080

  ingress:
    externalDNS: false
    host: ""
    path: "/"

registry:
  domain: quay.io

serviceMonitor:
  metricRelabelings: []
  relabelings: []

# Add seccomp to pod security context
podSecurityContext:
  runAsGroup: 1000
  runAsUser: 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Add seccomp to container security context
containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - "ALL"
  readOnlyRootFilesystem: true
  seccompProfile:
    type: RuntimeDefault
