{{- if .Values.security.letsencrypt.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "resource.default.name" . }}-tls
  namespace: {{ .Values.namespace }}
data:
  tls.crt: {{ .Values.certificate.monitoring.crtPem | quote }}
  tls.key: {{ .Values.certificate.monitoring.keyPem | quote }}
{{- end }}
