apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "resource.default.name" . }}-auth
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.server.ingress.host }}
    http:
      paths:
      - backend:
          service:
            #TODO: template name and port number
            name: grafana
            port:
              number: 3000
        #TODO: change path
        path: /grafana-fauth
        pathType: Prefix
