{{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{ else }}
apiVersion: networking.k8s.io/v1beta1
{{ end }}
kind: Ingress
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: https://$host/grafana-auth
    nginx.ingress.kubernetes.io/rewrite-target: /write
    {{- if .Values.server.ingress.externalDNS }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.server.ingress.host }}
    giantswarm.io/external-dns: managed
    {{- end }}   
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.server.ingress.host }}
    http:
      paths:
      - backend:
{{ if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          service:
            name: {{ include "resource.default.name" . }}
            port:
              number: {{ .Values.server.service.port }}
{{ else }}
          serviceName: {{ include "resource.default.name" . }}
          servicePort: {{ .Values.server.service.port }}
{{ end }}
        path: /{{ .Values.server.ingress.path }}/write
        pathType: ImplementationSpecific
