apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- if .Values.security.letsencrypt.enabled }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.server.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "resource.default.name" . }}
            port:
              number: {{ .Values.server.service.port }}
          path: /{{ .Values.server.ingress.analytics }}(/|$)(.*)
          pathType: ImplementationSpecific
