apiVersion: v1
kind: Service
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  ports:
  - name: web
    protocol: TCP
    port: {{ .Values.server.service.port }}
    targetPort: {{ .Values.server.port }}
  selector:
    {{- include "labels.selector" . | nindent 4 }}
