apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "resource.default.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  endpoints:
  - port: web
    relabelings:
    - replacement: macropower-analytics-panel-server
      targetLabel: app
    - replacement: {{ .codename }}
      targetLabel: cluster_id
    - replacement: management_cluster
      targetLabel: cluster_type
    - replacement: {{ .provider.kind }}
      targetLabel: provider
    - replacement: {{ .codename }}
      targetLabel: installation
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    - sourceLabels: [__meta_kubernetes_pod_container_name]
      targetLabel: container
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: node
    - sourceLabels: [__meta_kubernetes_node_label_role]
      targetLabel: role
    metricRelabelings:
    - action: "labeldrop"
      regex: "(user.*)"
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
